### ISSUE TITLE
Custom App 

### ISSUE THREAD

**Issue by sheetal2795** [netless-io/Fastboard-iOS#3]
I am using custom app, I am registering the same. 
I need to add the same in Option Panel. How can I do it?

**Comment by vince-hz** [comment]
Do you means you want to add your custom app to the option panel like this?
<img width="378" alt="image" src="https://github.com/netless-io/fastboard-iOS/assets/26054167/a3a3aac8-279f-472c-9cd2-c4bd67f6272b">

**Comment by sheetal2795** [comment]
Ye exactly for iOS

**Comment by vince-hz** [comment]
I had implemented it in our project flat. You can see the code in this link.

https://github.com/netless-io/flat-iOS/blob/f46fcc918668a79e5fa1abbee71824eca0b38ca7/Flat/Modules/ClassRoom/ClassroomFastboard/FastboardViewController.swift#L277

It only works for iPad. If you want to support iPhone, you should update `CompactFastRoomOverlay.customOperationPanel`.

Feel free to ask further questions!

**Comment by sheetal2795** [comment]
<img width="1096" alt="Screenshot 2023-10-12 at 3 08 12 PM" src="https://github.com/netless-io/fastboard-iOS/assets/125257118/004a5c0b-99f0-4a32-8ae5-4f75d7bda191">

Hey! Tried it in the phone, its giving me the above error. It has default options which can be added, however I cant add my custom app

**Comment by vince-hz** [comment]
Sorry, I forgot that the `customOperationPanel` is only valid for iPad overlay.
It's not configurable because iPhone has a little screen space.

What about you just add your custom button to your view by yourself.
If you want to align it to the default operation panel, you can use `overlay.operationPanel.view` to access the default operation view and made your own view constraints.

Here is an example:

``` swift
      fastRoom.joinRoom { _ in
            if let overlay = fastRoomView.overlay as? CompactFastRoomOverlay {
                let button = UIButton(type: .infoLight)
                self.view.addSubview(button)
                button.snp.makeConstraints { make in
                    make.left.equalTo(overlay.operationPanel.view!)
                    make.top.equalTo(overlay.operationPanel.view!.snp.bottom)
                }
            }
        }
```

Remind to add your button after join room succeed.

Hope the above helps you. @sheetal2795
